import Foundation

/// Renders a profile as a Markdown requirements block.
///
/// The output must be **byte-identical when re-rendered from the same
/// artifact**, or `--check` reports drift on every run and the CI gate is
/// worthless. So nothing here reads the clock, the machine, or anything else
/// live — every value comes from the `Profile`, including its timestamp. That
/// is the practical payoff of the artifact being the source of truth
/// (ARCHITECTURE #7).
public enum MarkdownRenderer {

    /// Renders the block that goes between the injection markers.
    public static func requirementsBlock(_ profile: Profile) -> String {
        var lines: [String] = []

        lines.append("### Resource Requirements")
        lines.append("")
        lines.append("Measured, not estimated — \(profile.runs.count) "
            + "run\(profile.runs.count == 1 ? "" : "s") of `\(profile.command.joined(separator: " "))`.")
        lines.append("")

        lines.append("| | Measured |")
        lines.append("|---|---|")
        lines.append("| **Recommended RAM** | \(bytes(profile.recommendedRAMBytes)) |")
        lines.append("| Peak RAM | \(statistic(profile.peakRAMBytes, bytes)) |")

        // The split is only interesting when a service actually held memory;
        // showing "0 B external" on every project would be noise.
        if profile.externalPeakRAMBytes.max > 0 {
            lines.append("| — own processes | \(statistic(profile.ownPeakRAMBytes, bytes)) |")
            let services = profile.externalServices.joined(separator: ", ")
            lines.append(
                "| — \(services.isEmpty ? "external services" : services) "
                    + "| \(statistic(profile.externalPeakRAMBytes, bytes)) |"
            )
        }

        lines.append("| Peak CPU | \(statistic(profile.peakCPU, percent)) |")
        lines.append("| Wall clock | \(statistic(profile.wallClockSeconds, seconds)) |")
        if profile.diskReadBytes.max > 0 {
            lines.append("| Disk read | \(statistic(profile.diskReadBytes, bytes)) |")
        }
        if profile.diskWrittenBytes.max > 0 {
            lines.append("| Disk write | \(statistic(profile.diskWrittenBytes, bytes)) |")
        }
        lines.append("| Peak swap-out rate | \(swapRate(profile)) |")

        lines.append("")
        lines.append("Measured on \(profile.machine.summary).")

        // Everything below is the honesty half. A requirements block that
        // reported only the numbers would imply a confidence the measurement
        // does not always have.
        var caveats: [String] = []

        if profile.conditions.contended {
            caveats.append(
                "Other work used \(percent(profile.conditions.contendingCPU.median)) CPU during "
                    + "measurement, so these figures are soft."
            )
        }
        if profile.peakRAMBytes.relativeSpread > 0.2 {
            caveats.append(
                "Peak RAM varied \(percent(profile.peakRAMBytes.relativeSpread)) across runs."
            )
        }
        if profile.conditions.worstThermal.isThrottlingLikely {
            caveats.append(
                "The machine reached thermal state "
                    + "`\(profile.conditions.worstThermal.rawValue)`, so it was likely throttling."
            )
        }
        if !profile.timedOutRuns.isEmpty {
            caveats.append("\(profile.timedOutRuns.count) run(s) hit the time limit and "
                + "measured a hang rather than the work.")
        }
        if !profile.underObservedRuns.isEmpty {
            caveats.append("\(profile.underObservedRuns.count) run(s) finished too fast to be "
                + "sampled meaningfully.")
        }
        if !profile.capabilityGaps.isEmpty {
            caveats.append(
                "Not measured on this machine: "
                    + profile.capabilityGaps.map { "`\($0)`" }.joined(separator: ", ")
                    + " — see `sitrep doctor`."
            )
        }

        if !caveats.isEmpty {
            lines.append("")
            for caveat in caveats { lines.append("> \(caveat)") }
        }

        lines.append("")
        lines.append(
            "<sub>Generated by [mac-sitrep](https://github.com/jasonli-git/mac-sitrep) "
                + "\(profile.toolVersion) from `\(profile.version)` on "
                + "\(isoDay(profile.generatedAt)).</sub>"
        )

        return lines.joined(separator: "\n")
    }

    // MARK: - Formatting
    //
    // Local rather than shared with `Format`: terminal output can change freely,
    // but any change here alters every published block and trips every `--check`
    // in every repo. Keeping them separate makes that coupling explicit.

    static func bytes(_ value: UInt64) -> String {
        Format.bytes(value)
    }

    static func bytes(_ value: Double) -> String {
        Format.bytes(UInt64(max(0, value)))
    }

    static func percent(_ fraction: Double) -> String {
        String(format: "%.0f%%", fraction * 100)
    }

    static func seconds(_ value: Double) -> String {
        value < 10 ? String(format: "%.2f s", value) : String(format: "%.0f s", value)
    }

    /// Median with the range in parentheses, omitting the range when a
    /// measurement was perfectly stable.
    static func statistic(_ value: Statistic, _ format: (Double) -> String) -> String {
        value.min == value.max
            ? format(value.median)
            : "\(format(value.median)) _(\(format(value.min)) – \(format(value.max)))_"
    }

    static func swapRate(_ profile: Profile) -> String {
        profile.conditions.peakSwapOutsPerSecond > 0
            ? String(format: "%.1f/s", profile.conditions.peakSwapOutsPerSecond)
            : "0 — no swapping"
    }

    /// Date only. The time of day would add churn to the published block for no
    /// information a reader can use.
    static func isoDay(_ date: Date) -> String {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd"
        formatter.timeZone = TimeZone(identifier: "UTC")
        return formatter.string(from: date)
    }
}
