import Foundation

/// Writes a generated block into a hand-written document.
///
/// Only the region between the markers is ever touched. The rest of the file —
/// which someone wrote by hand — must survive byte-for-byte, so this never
/// rewrites a whole document and refuses outright when the markers are in a
/// state it cannot interpret.
public enum ReadmeInjector {

    public static let startMarker = "<!-- sitrep:requirements:start -->"
    public static let endMarker = "<!-- sitrep:requirements:end -->"

    /// Warns off hand-editing, since the next `sitrep export` would discard it.
    static let generatedNotice = "<!-- generated by sitrep — do not edit by hand -->"

    public enum InjectionError: Error, CustomStringConvertible, Equatable {
        case unbalancedMarkers(starts: Int, ends: Int)
        case endBeforeStart
        case fileNotFound(String)

        public var description: String {
            switch self {
            case let .unbalancedMarkers(starts, ends):
                """
                markers are unbalanced (\(starts) start, \(ends) end). Expected \
                exactly one of each, or none. Fix the file by hand — rewriting \
                it automatically could destroy content.
                """
            case .endBeforeStart:
                "the end marker appears before the start marker"
            case let .fileNotFound(path):
                "no file at \(path)"
            }
        }
    }

    public enum Outcome: Equatable {
        /// The block replaced existing content between markers.
        case replaced
        /// A new section was appended because the file had no markers.
        case appended
        /// The file already contained exactly this block.
        case unchanged

        public var summary: String {
            switch self {
            case .replaced: "replaced the existing block"
            case .appended: "appended a new section"
            case .unchanged: "already up to date"
            }
        }
    }

    /// Produces the document that *would* be written, without touching disk.
    ///
    /// Split out so `--check` and `--inject` share exactly one implementation.
    /// A drift gate that compared against a second, subtly different renderer
    /// would report drift that does not exist.
    public static func apply(
        block: String, to document: String
    ) throws -> (document: String, outcome: Outcome) {
        let starts = occurrences(of: startMarker, in: document)
        let ends = occurrences(of: endMarker, in: document)

        guard starts == ends, starts <= 1 else {
            throw InjectionError.unbalancedMarkers(starts: starts, ends: ends)
        }

        let wrapped = """
        \(startMarker)
        \(generatedNotice)

        \(block)

        \(endMarker)
        """

        guard starts == 1 else {
            // No markers: append rather than guessing where the section belongs.
            // Inserting at a heuristic position would reorder someone's document.
            let separator = document.hasSuffix("\n") ? "\n" : "\n\n"
            return (document + separator + wrapped + "\n", .appended)
        }

        guard let startRange = document.range(of: startMarker),
              let endRange = document.range(of: endMarker),
              startRange.lowerBound < endRange.lowerBound
        else {
            throw InjectionError.endBeforeStart
        }

        let updated = document.replacingCharacters(
            in: startRange.lowerBound..<endRange.upperBound, with: wrapped
        )
        return (updated, updated == document ? .unchanged : .replaced)
    }

    /// Writes the block into the file at `path`.
    public static func inject(block: String, into path: String) throws -> Outcome {
        let document = try read(path)
        let (updated, outcome) = try apply(block: block, to: document)

        // Skipping the write when nothing changed keeps the file's mtime stable,
        // so a no-op export does not look like a modification to git or a watcher.
        if outcome != .unchanged {
            try updated.write(toFile: path, atomically: true, encoding: .utf8)
        }
        return outcome
    }

    /// Whether the file already carries exactly this block.
    ///
    /// This is the CI gate: it answers "would injecting change anything?" using
    /// the same code path injection uses.
    public static func isUpToDate(block: String, at path: String) throws -> Bool {
        let document = try read(path)
        let (updated, _) = try apply(block: block, to: document)
        return updated == document
    }

    /// Extracts the current block, or `nil` when the file has no markers.
    public static func currentBlock(at path: String) throws -> String? {
        let document = try read(path)
        guard let start = document.range(of: startMarker),
              let end = document.range(of: endMarker),
              start.upperBound < end.lowerBound
        else { return nil }

        return String(document[start.upperBound..<end.lowerBound])
            .trimmingCharacters(in: .whitespacesAndNewlines)
    }

    static func read(_ path: String) throws -> String {
        guard FileManager.default.fileExists(atPath: path) else {
            throw InjectionError.fileNotFound(path)
        }
        return try String(contentsOfFile: path, encoding: .utf8)
    }

    static func occurrences(of needle: String, in haystack: String) -> Int {
        var count = 0
        var searchRange = haystack.startIndex..<haystack.endIndex

        while let found = haystack.range(of: needle, range: searchRange) {
            count += 1
            searchRange = found.upperBound..<haystack.endIndex
        }
        return count
    }
}

/// Badge data for shields.io's endpoint format.
///
/// A badge is the requirements block compressed to one glance. Emitted as a file
/// the project commits and points a shields.io endpoint URL at, so rendering it
/// costs no service and no network call from us.
public enum BadgeRenderer {

    public struct Badge: Encodable {
        public let schemaVersion = 1
        public let label: String
        public let message: String
        public let color: String
    }

    public static func peakRAM(_ profile: Profile) -> Badge {
        Badge(
            label: "peak RAM",
            message: Format.bytes(UInt64(profile.peakRAMBytes.median)),
            // Colour tracks how much of *this* machine the workload needed, which
            // is the only honest scale available — the reader's machine is
            // unknown, and pretending otherwise would be a cross-machine claim
            // the project refuses to make (SPEC non-goals).
            color: color(
                fraction: profile.peakRAMBytes.median
                    / Double(profile.machine.physicalMemoryBytes)
            )
        )
    }

    static func color(fraction: Double) -> String {
        switch fraction {
        case ..<0.25: "brightgreen"
        case ..<0.50: "green"
        case ..<0.75: "yellow"
        default: "orange"
        }
    }

    public static func json(_ badge: Badge) throws -> String {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        return String(decoding: try encoder.encode(badge), as: UTF8.self)
    }
}
